//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppZADANIE.Comp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_Ord
    {
        public int ID { get; set; }
        public Nullable<int> ID_prod { get; set; }
        public Nullable<int> ID_ord { get; set; }
        public Nullable<int> Prod_count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
